language: node_js

branches:
  only:
    - develop

before_script:
  - npm install -g harp
script:

after_success:
  - harp compile -o dist
  - echo "zuqichen.com" > dist/CNAME
  - cp README.md dist

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  target_branch: master
  on:
    branch: master

after_deploy:
  - rm -rf dist
