language: node_js

node_js:
  - "6"

branches:
  only:
  - develop

install:
  - npm install -g harp

script:
  - harp compile -o dist

after_success:
  - echo "zuqichen.com" > dist/CNAME
  - cp README.md dist

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  target_branch: master
  on:
    branch: develop

after_deploy:
  - rm -rf dist
